repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '^(demand|production)\.py$'
      - id: ruff-format
        exclude: '^(demand|production)\.py$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports, --show-error-codes]
        exclude: '^(demand|production)\.py$'